batch_size_perc: 0.01
dis_iter: 1
dis_opt_args:
- 0.0002
- - 0.5
  - 0.9
gen_iter: 1
gen_opt_args:
- 0.0002
- - 0.5
  - 0.9
hold_out: 100
loss: cross_entropy
max_norm_dis: .01
max_norm_gen: .01
num_simulations: 1000000
log_dataloader: False
